/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management_;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

    
/**
 *
 * @author kriaa
 */
public class IssueBook extends javax.swing.JFrame {
    
        Connection con=Connect.Connection();
        PreparedStatement pst=null;
        ResultSet rs=null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IssueBook.class.getName());

    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        initComponents();
       
        SimpleDateFormat  dat=new SimpleDateFormat("dd/MM/yyyy ");
         Date d=new Date();
         txtissue.setText(dat.format(d));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtbookid = new javax.swing.JTextField();
        txtstudentid = new javax.swing.JTextField();
        txtbookname = new javax.swing.JTextField();
        txtissue = new javax.swing.JTextField();
        txtduedate = new javax.swing.JTextField();
        btnissue = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/isue.jpg"))); // NOI18N
        jLabel1.setText("Issue Book");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 63, 272, 75));

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close icon.png"))); // NOI18N
        btnclose.addActionListener(this::btncloseActionPerformed);
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 0, 69, 65));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Book ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 213, 92, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Student ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 290, 88, 41));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Book Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 81, 38));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Issue Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 469, 83, 42));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Due Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 552, 123, 44));

        txtbookid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 213, 339, 40));

        txtstudentid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtstudentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 290, 339, 39));

        txtbookname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtbookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 339, 43));

        txtissue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 469, 339, 42));

        txtduedate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtduedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 552, 339, 41));

        btnissue.setBackground(new java.awt.Color(153, 0, 0));
        btnissue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnissue.setForeground(new java.awt.Color(255, 255, 255));
        btnissue.setText("Issue Book");
        btnissue.addActionListener(this::btnissueActionPerformed);
        getContentPane().add(btnissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 665, 131, 44));

        btnsearch.setBackground(new java.awt.Color(153, 0, 0));
        btnsearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch.setText("Search");
        btnsearch.addActionListener(this::btnsearchActionPerformed);
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 214, 115, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/All Page Backgraound.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1090, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
         if(txtbookid.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Please enter Book ID and Search it again");
                txtbookid.requestFocus();
         }
         else{
             try {
                 pst=con.prepareStatement("SELECT * FROM BOOK WHERE ID=?");
                 pst.setString(1, txtbookid.getText());
                 rs=pst.executeQuery();
                 if(rs.next()){
                     txtbookname.setText(rs.getString(2));
                 }
                 
                 
             } catch (SQLException ex) {
                 System.getLogger(IssueBook.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
             }
         }
           
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnissueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnissueActionPerformed
        // TODO add your handling code here:
                                              

    if (txtbookid.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(this,
                "Please enter Book ID and Search it again");
        txtbookid.requestFocus();
        return;
    }

    if (txtstudentid.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(this,
                "Please enter Student ID");
        txtstudentid.requestFocus();
        return;
    }

    if (txtbookname.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(this,
                "Please search the Book ID first");
        return;
    }

    if (txtduedate.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(this,
                "Please enter Due Date");
        txtduedate.requestFocus();
        return;
    }

    try {

        // Check book status first
        pst = con.prepareStatement(
                "SELECT status FROM book WHERE id=?"
        );

        pst.setString(1, txtbookid.getText().trim());
        rs = pst.executeQuery();

        if (rs.next()) {

            if ("ISSUED".equalsIgnoreCase(rs.getString("status"))) {
                JOptionPane.showMessageDialog(this,
                        "This book is already issued.");
                return;
            }

        } else {
            JOptionPane.showMessageDialog(this,
                    "Book ID not found.");
            return;
        }

        // Issue the book
        pst = con.prepareStatement(
                "UPDATE book SET status=?, issuedate=?, duedate=?, studentid=? WHERE id=?"
        );

        pst.setString(1, "ISSUED");
        pst.setString(2, txtissue.getText().trim());
        pst.setString(3, txtduedate.getText().trim());
        pst.setString(4, txtstudentid.getText().trim());
        pst.setString(5, txtbookid.getText().trim());

        int result = pst.executeUpdate();

        if (result > 0) {

            JOptionPane.showMessageDialog(this,
                    "BOOK ISSUED SUCCESSFULLY");

            txtbookid.setText("");
            txtbookname.setText("");
            txtstudentid.setText("");
            txtduedate.setText("");

            SimpleDateFormat dat =
                    new SimpleDateFormat("dd/MM/yyyy");

            txtissue.setText(dat.format(new Date()));

        } else {

            JOptionPane.showMessageDialog(this,
                    "Book could not be issued.");

        }

    } catch (SQLException ex) {

        JOptionPane.showMessageDialog(this,
                "Database Error: " + ex.getMessage());
    }

    }//GEN-LAST:event_btnissueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IssueBook().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnissue;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtduedate;
    private javax.swing.JTextField txtissue;
    private javax.swing.JTextField txtstudentid;
    // End of variables declaration//GEN-END:variables
}
