/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management_;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kriaa
 */
public class ReturnBook extends javax.swing.JFrame {
   Connection con=Connect.Connection();
    PreparedStatement pst =null;
    ResultSet rs=null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReturnBook.class.getName());

    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtstudentid = new javax.swing.JTextField();
        txtbookid = new javax.swing.JTextField();
        txtbookname = new javax.swing.JTextField();
        txtstudentname = new javax.swing.JTextField();
        txtissuedate = new javax.swing.JTextField();
        txtduedate = new javax.swing.JTextField();
        btnreturn = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/isue.jpg"))); // NOI18N
        jLabel1.setText("Return Book");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 36, 243, 92));

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close icon.png"))); // NOI18N
        btnclose.addActionListener(this::btncloseActionPerformed);
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1071, 0, 67, 57));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Student ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 194, 102, 41));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Book ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 256, 102, 46));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Book Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 321, 102, 42));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Student Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 390, 102, 42));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Issue Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 452, 102, 41));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Due Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 512, 102, 40));

        txtstudentid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtstudentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 197, 429, 41));

        txtbookid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 257, 429, 46));

        txtbookname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtbookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 322, 429, 42));

        txtstudentname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtstudentname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 392, 429, 41));

        txtissuedate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtissuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 451, 429, 44));

        txtduedate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtduedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 513, 429, 41));

        btnreturn.setBackground(new java.awt.Color(153, 0, 0));
        btnreturn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnreturn.setForeground(new java.awt.Color(255, 255, 255));
        btnreturn.setText("Return");
        btnreturn.addActionListener(this::btnreturnActionPerformed);
        getContentPane().add(btnreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 639, 99, 35));

        btnsearch.setBackground(new java.awt.Color(153, 0, 0));
        btnsearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch.setText("Search");
        btnsearch.addActionListener(this::btnsearchActionPerformed);
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 194, -1, 41));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/All Page Backgraound.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1140, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        

    if (txtstudentid.getText().trim().equals("")) {

        JOptionPane.showMessageDialog(this,
                "Please Enter Student ID and Search it");

        txtstudentid.requestFocus();
        return;
    }

    try {

        pst = con.prepareStatement(
                "SELECT student.name AS student_name, " +
                "book.id AS book_id, " +
                "book.name AS book_name, " +
                "book.issuedate, " +
                "book.duedate " +
                "FROM book " +
                "INNER JOIN student ON book.studentid = student.id " +
                "WHERE student.id=? AND book.status='ISSUED'"
        );

        pst.setInt(1, Integer.parseInt(txtstudentid.getText().trim()));

        rs = pst.executeQuery();

        if (rs.next()) {

            txtbookid.setText(rs.getString("book_id"));
            txtstudentname.setText(rs.getString("student_name"));
            txtbookname.setText(rs.getString("book_name"));
            txtissuedate.setText(rs.getString("issuedate"));
            txtduedate.setText(rs.getString("duedate"));

        } else {

            JOptionPane.showMessageDialog(this,
                    "No issued book found for this Student ID.");

        }

    } catch (NumberFormatException ex) {

        JOptionPane.showMessageDialog(this,
                "Student ID must be a number.");

    } catch (SQLException ex) {

        JOptionPane.showMessageDialog(this,
                "Database Error: " + ex.getMessage());
    

            
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        // TODO add your handling code here:
       

  

    if (txtstudentid.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(this,
                "Please Enter Student ID and Search it");
        return;
    }

    if (txtbookid.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(this,
                "Please Search Student ID first");
        return;
    }

    try {

        pst = con.prepareStatement(
                "UPDATE book SET status=?, issuedate=NULL, " +
                "duedate=NULL, studentid=NULL " +
                "WHERE id=? AND studentid=?"
        );

        pst.setString(1, "NOT-ISSUED");
        pst.setString(2, txtbookid.getText().trim());
        pst.setString(3, txtstudentid.getText().trim());

        int result = pst.executeUpdate();

        if (result > 0) {

            JOptionPane.showMessageDialog(this,
                    "BOOK RETURNED SUCCESSFULLY");

            txtstudentid.setText("");
            txtbookid.setText("");
            txtbookname.setText("");
            txtstudentname.setText("");
            txtissuedate.setText("");
            txtduedate.setText("");

        } else {

            JOptionPane.showMessageDialog(this,
                    "Book could not be returned.");
        }

    } catch (SQLException ex) {

        JOptionPane.showMessageDialog(this,
                "Database Error: " + ex.getMessage());
    


        }
    }//GEN-LAST:event_btnreturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReturnBook().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnreturn;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtduedate;
    private javax.swing.JTextField txtissuedate;
    private javax.swing.JTextField txtstudentid;
    private javax.swing.JTextField txtstudentname;
    // End of variables declaration//GEN-END:variables
}
